collections:
  - common
  - purescript

excludes:
  - .cspell.json
  - README.md
  - bower.json
  - package.json
  - spago.dhall

render_context:
  project:
    name: purescript-roman
    description: Convert between Roman numerals and base 10.
    version: 0.2.1
    verbose_name: PureScript Roman
    repository: https://github.com/JoelLefkowitz/purescript-roman
    codacy_id: ec61f81349714facb1a2d53d317c77d6

  author:
    author: joellefkowitz
    author_email: joellefkowitz@hotmail.com
    verbose_author: Joel Lefkowitz

clear_top_level: true
logical_grouping: true

loader_paths:
  - docs
