language: node_js

os: linux
dist: xenial
node_js: 14.8.0

before_install:
    - curl -sSL https://get.haskellstack.org/ | sh
    - npm install -g purescript --unsafe-perm=true
    - npm install -g spago
    - npm install -g grunt-cli
    - npm install

cache:
    - npm

jobs:
    include:
        - stage: Linters
          script: grunt lint

        - stage: Unit tests
          script: grunt tests:unit
