language: node_js

os: linux
dist: xenial
node_js: 14.8.0
    
before_install:

    # Install PureScript dependencies
    - sudo apt-get install libncurses5
    - sudo apt-get install libc6

    # Install PureScript from its binary
    - curl -L https://github.com/purescript/purescript/releases/download/v0.14.1/linux64.tar.gz --output linux64.tar.gz
    - tar -xzf linux64.tar.gz purescript/purs --strip-components=1
    - sudo mv purs /usr/local/bin/purs
    
    # Test the PureScript installation
    - purs --version
    
    # Global npm executables needed to run build stages
    - npm install -g spago
    - npm install -g grunt-cli
    
    # Make dev dependencies available for all build stages
    - npm install

cache:
    - npm

jobs:
    include:
        - stage: Linters
          script: grunt lint

        - stage: Unit tests
          script: grunt tests:unit
